### PR TITLE
SLING-8278 improve chrome audit score

### PR DESCRIPTION
**Pull request by reusr1**
increase accessibility and seo score to 100/100, best practices to 87/100

### CODE REVIEW

**Comment by rombert** [comment]
A SonarQube report for the changes added _only by this pull request_ was generated. Please review it at https://builds.apache.org/job/Sling/job/sling-org-apache-sling-starter-content/job/PR-1/1/artifact/target/sonar/issues-report/issues-report-light.html

**Comment by klcodanr** [comment]
What if instead of making the text black, we changed the body color to color: rgb(96,96,96); and removed the color from the H1 tag. Personally, I find this a bit more visually appealing and its WCAG 2.0 AA compliant:

screen shot 2019-03-06 at 8 11 16 am

**Comment by rombert** [comment]
Sounds good to me @klcodanr. @reusr1 , what do you think?

**Comment by reusr1** [comment]
#606060 is unfortunately not AAA compliant, #505050 may be better. Just from my pov the page is actually kind of hard to read to begin with (may be OS dependent rendering)

image

here's a version with #555 and a .body font-weight: 400 (current is 300). Way easier to read
image

**Comment by klcodanr** [comment]
@reusr1 Like it! Can you commit the changes into the PR and I'll get this PR merged?

**Comment by reusr1** [comment]
> @reusr1 Like it! Can you commit the changes into the PR and I'll get this PR merged?

@klcodanr @rombert made the change as requested. I also darkened the link color a bit to make it AAA compliant

@rombert I switched the getSessionInfo over to the async method and also added an unknown state (initial state) to make it less 'flashy'. 

the only thing missing now is http/2 support to get to a perfect score

image

**Pull request merged**
